name = "strangers-backend"
main = "backend/worker.mjs"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "api.strangers.hackins.club/*"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "strangers-db"
database_id = "4145ab06-f39e-42db-af81-d3301da86655"