name = "strangers-backend"
main = "backend/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "strangers-db"
database_id = "4145ab06-f39e-42db-af81-d3301da86655"