name = "strangers-backend"
main = "backend/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "strangers-db"
database_id = "MESSAGE_ME_TO_FILL_THIS" # Will need user to fill this after creation
